services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=chingu
      - POSTGRES_PASSWORD=chingu
      - POSTGRES_DB=dashboard
      - PGPORT=5433
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres-test:
    container_name: postgres-test
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=chingu
      - POSTGRES_PASSWORD=chingu
      - POSTGRES_DB=dashboard
      - PGPORT=5434
    ports:
      - "5434:5434"
    volumes:
      - pgdata-test:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=chinguadmin@chingu.com
      - PGADMIN_DEFAULT_PASSWORD=chingu5432
    depends_on:
      - postgres
    ports:
      - "4000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  api:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://chingu:chingu@postgres:5433/dashboard?schema=public
    ports:
      - "8000:8000"
      - "5555:5555"
    depends_on:
      - postgres
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    command: ['yarn', 'start:dev']

volumes:
  pgdata:
  pgdata-test:
  pgadmin-data:

networks:
  default:
    name: chingu-dashboard-be
