name: Lint & Test Workflow

on:
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Run Eslint
        run: yarn lint

      - name: Run Jest tests
        run: |
          if [ ${{ github.event.pull_request.base.ref }} == "main" ]; then
            yarn test
          fi
        env:
          MJ_APIKEY_PUBLIC: ${{ secrets.MJ_APIKEY_PUBLIC }},
          MJ_APIKEY_PRIVATE: ${{ secrets.MJ_APIKEY_PRIVATE }}

      - name: Apply all pending migrations to the test database
        run: npx prisma db push --accept-data-loss
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}

      - name: Run e2e tests
        run: |
          if [ ${{ github.event.pull_request.base.ref }} == "main" ]; then
            yarn test:e2e
          fi
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
